# set variables
export NULLCMD=bat

# change zsh options

# create aliases

alias ls='exa -1aFh --git --icons'
alias exa='exa -1aFh --git --icons'
alias man='batman'
alias trail='<<<${(F)path}'

# customize prompt
PROMPT='
%n@%m %1~ %L %# '

RPROMPT='%*'

# add locations to $PATH
export PATH=$PATH:$HOME/.local/bin

# functions
function mkcd() {
  mkdir -p "$@" && cd "$_";
}

# zsh plugins
