
[window]
dynamic_title = true
opacity = 0.85
title = "Terminal"

[font]
size = 12.0
normal = { family = "Monaspace Argon", style = "Regular" }

[cursor]
style = { shape = "Underline", blinking = "Off" }
thickness = 0.20

[mouse]
hide_when_typing = true

[general]
live_config_reload = true

[terminal]

shell = "C:/Users/joao/scoop/apps/pwsh/current/pwsh.exe -WorkingDirectory ~"

