live_config_reload = true

[window]
dynamic_title = true
opacity = 0.85
title = "Terminal"

[font]
size = 12.0
normal = { family = "Fira Code Retina", style = "Regular" }

[cursor]
style = { shape = "Underline", blinking = "Off" }
thickness = 0.20

[mouse]
hide_when_typing = true

