[cursor]
shape = "Underline"

[font]
size = 12.0

[font.normal]
family = "Fira Code Retina"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.85
title = "Terminal"

[window.dimensions]
columns = 0
lines = 0
