- hosts: localhost
  connection: local
  gather_facts: no
  become: yes # todo: every created file is owned by root
  tasks:
    - name: create user
      user:
        name: joao # todo: add to docker group
        shell: /bin/zsh # todo: check if it's really working
        state: present
      register: user
    - name: "create symbolic links"
      file:
        src: "{{ playbook_dir }}/../{{ item.src }}" # todo: get absolute path
        dest: "{{ item.dest }}"
        force: yes
        state: link
      loop:
        - { src: "zsh/.zshrc",               dest: "{{ user.home }}/.zshrc" }
        - { src: "zsh/.zshenv",              dest: "{{ user.home }}/.zshenv" }
        - { src: "alacritty/alacritty.yml", dest: "{{ user.home }}/.alacritty.yml" }
        - { src: "ssh/config",               dest: "{{ user.home }}/.ssh/config" }
    - name: check already installed packages
      block:
        - name: check if cargo is installed # todo: causes error on console
          shell: command -v cargo
          register: cargo_exists
          ignore_errors: yes
        - name: check if docker is installed # todo: causes error on console, show as changed
          shell: command -v docker
          register: docker_exists
          ignore_errors: yes
        - name: check if zsh-syntax-highlighting is installed
          stat:
            path: "{{ user.home }}/.zsh/zsh-syntax-highlighting"
          register: zsh_syntax_highlighting
        - name: check if zsh-autosuggestions is installed
          stat:
            path: "{{ user.home }}/.zsh/zsh-autosuggestions"
          register: zsh_autosuggestions
    - name: install packages
      apt:
        update_cache: yes
        name:
          - gcc
          - python3-dev
          - exa
          - bat
          - zsh
          - git
          - emacs
          - tree
          - golang-go
        state: present
    - name: setup zsh
      block:
        - name: create .zsh directory
          file:
            path: "{{ user.home }}/.zsh"
            state: directory
            mode: '0755'
        - name: install zsh plugins
          block:
            - name: install zsh-syntax-highlighting
              when: not zsh_syntax_highlighting.stat.exists # todo: show as changed
              git:
                repo:  https://github.com/zsh-users/zsh-syntax-highlighting.git
                dest: "{{ user.home }}/.zsh/zsh-syntax-highlighting"
            - name: install zsh-autosuggestions
              when: not zsh_autosuggestions.stat.exists # todo: show as changed
              git:
                repo: https://github.com/zsh-users/zsh-autosuggestions.git
                dest: "{{ user.home }}/.zsh/zsh-autosuggestions"
    - name: install docker
      when: docker_exists is failed
      shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
    - name: update python to latest version
      apt:
        name: python3
        state: latest
    - name: "install pip packages" # todo: needs dependencies to compile
      pip:
        extra_args: --compile
        name:
          - trash-cli
    - name: install rust
      when: cargo_exists is failed
      block:
      - name: download rust installer
        get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'
        tags:
          - rust
      - name: install rust/cargo # todo: show as changed
        shell: /tmp/sh.rustup.rs -y
        tags:
          - rust
    - name: install alacritty
      when: cargo_exists is success
      community.general.cargo:
        name: alacritty
        state: present
