#!/usr/bin/env zsh

# create aliases
alias ls='exa --long --all --classify --header --icons'
alias trail='<<<${(F)path}'
alias python='python3'

alias emacs='emacs --no-window-system'

alias gc='git commit -m'
alias gb='git checkout -b'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias gl='git log'
alias gam='git commit --amend'
alias gp='git push'

alias t1='tree -L 1'
alias t2='tree -L 2'
alias t3='tree -L 3'
