#!/usr/bin/env zsh

epoch() {
  if [ ${#1} -lt 13 ]; then
    token="$1"
  else
    token="${1::-3}"
  fi
  python3 -c "import time; print('%s' % time.strftime('%c',time.localtime($token)))"
}

exists() {
  command -v $1 >/dev/null 2>&1
}

capitalize() {
  printf '%s' "$1" | head -c 1 | tr [:lower:] [:upper:]
  printf '%s' "$1" | tail -c '+2'
}

mkcd() {
  mkdir -p "$@" && cd "$_"
}
