#!/usr/bin/env zsh

exists() {
  command -v $1 >/dev/null 2>&1
}

capitalize() {
  printf '%s' "$1" | head -c 1 | tr [:lower:] [:upper:]
  printf '%s' "$1" | tail -c '+2'
}

mkcd() {
  mkdir -p "$@" && cd "$_"
}
