#!/usr/bin/env zsh

export SDL_GAMECONTROLLERCONFIG="030000004c050000cc09000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,platform:Linux"

export NULLCMD=bat

# irc variables
export IRCNAME=*
export IRCPORT=6667
export IRCNICK=un_known
export IRCUSER=un_known

# go variables
export GOPATH=$HOME/go
export GOROOT=/usr/lib/go

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

export NVIM_HOME="$HOME/.config/nvim"

typeset -U path

path=(
  $path
  "$HOME/.local/bin"
  "$GOROOT/bin"
  "$GOPATH/bin"
  "$HOME/.poetry/bin"
  "$HOME/.local/share/gem/ruby/3.0.0/bin"
  "$HOME/.yarn/bin"
  "$HOME/.config/yarn/global/node_modules/.bin"
)
