# set variables
# change zsh options
# create aliases
alias ls='ls -lAFh'

# customize prompt
PROMPT='
%n@%m %1~ %L %# '

RPROMPT='%*'

# add locations to $PATH

# functions
function mkcd() {
  mkdir -p "$@" && cd "$_";
}

# zsh plugins
